### ISSUE TITLE
symbolic link crashes installer

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#1275]
## Describe the bug
I perform a standard installation on my hosting provider. The hosting provider has 2 folders : public_html and private_html so you can make a difference between files you can access on http (public_html) and https (private_html). In my case the private_html folder is just a symbolic link to the public_html because my https content is the same as my http.

In the step where the modules get installed, hte installer crashes with the following error message : 

``Fatal error: Uncaught League\Flysystem\SymbolicLinkEncountered: Unsupported symbolic link encountered at location /home/icmsdev/domains/impresscms.dev/private_html in /home/icmsdev/domains/impresscms.dev/vendor/league/flysystem/src/SymbolicLinkEncountered.php:23 Stack trace: #0 /home/icmsdev/domains/impresscms.dev/vendor/league/flysystem/src/Local/LocalFilesystemAdapter.php(207): League\Flysystem\SymbolicLinkEncountered::atLocation('/home/icmsdev/d...') #1 /home/icmsdev/domains/impresscms.dev/core/Providers/RouterServiceProvider.php(303): League\Flysystem\Local\LocalFilesystemAdapter->listContents('.htpasswd', false) #2 /home/icmsdev/domains/impresscms.dev/core/Providers/RouterServiceProvider.php(356): ImpressCMS\Core\Providers\RouterServiceProvider->findAccessibleItemsFromPath(Object(League\Flysystem\Filesystem), '', '', false, Array, Array) #3 /home/icmsdev/domains/impresscms.dev/core/Providers/RouterServiceProvider.php(437): ImpressCMS\Core\Providers\RouterServiceProvider->getLegacyRegexp() #4 /home/icmsdev/domains/imp in /home/icmsdev/domains/impresscms.dev/vendor/league/flysystem/src/SymbolicLinkEncountered.php on line 23
``

## Expected behavior
The installer does the installation, without being confused by the presence of a non-used symbolic link.

## Server
 - PHP version: 7.4
 - PHP is 32/64bit: 64
 - HTTP Server : [Apache, nginx] apache
 - HTTP Server version:  2.4
 - HTTP Server is 32/64 bit: 64

**Comment by fiammybe** [comment]
closed in #1280
