### ISSUE TITLE
Uncaught exception in libraries\icms\file\MediaUploadHandler.php

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#288]
```
Message: Using $this when not in object context
Code: 0
File: C:\xampp71\htdocs\unifya7\libraries\icms\file\MediaUploadHandler.php
Line: 691
Trace: 
#0 C:\xampp71\htdocs\unifya7\modules\downloads\class\DownloadHandler.php(55): icms_file_MediaUploadHandler::setErrors('Unknown filetyp...')
#1 C:\xampp71\htdocs\unifya7\modules\downloads\class\DownloadHandler.php(45): DownloadsDownloadHandler->checkMimeType()
#2 C:\xampp71\htdocs\unifya7\include\functions.php(1755): DownloadsDownloadHandler->__construct(Object(icms_db_legacy_PdoDatabase))
#3 C:\xampp71\htdocs\unifya7\include\functions.php(1011): icms_getModuleHandler('download', 'downloads', 'downloads', true)
#4 C:\xampp71\htdocs\unifya7\modules\downloads\icms_version.php(100): icms_getTablesArray('downloads', Array)
#5 C:\xampp71\htdocs\unifya7\libraries\icms\module\Object.php(284): include('C:\\xampp71\\htdo...')
#6 C:\xampp71\htdocs\unifya7\modules\system\admin\modules\modules.php(105): icms_module_Object->loadInfo('downloads', false)
#7 C:\xampp71\htdocs\unifya7\modules\system\admin\modules.php(67): xoops_module_list()
#8 C:\xampp71\htdocs\unifya7\modules\system\admin.php(117): include_once('C:\\xampp71\\htdo...')
#9 C:\xampp71\htdocs\unifya7\htdocs\index.php(114): require('C:\\xampp71\\htdo...')
#10 {main}
```

**Comment by skenow** [comment]
I don't believe this is an error with the core, but rather with the module. Looking at the trace, and verifying in the module's code, downloads calls the setErrors function statically, and the function is not declared as such. Trying to set properties for an object that doesn't exist is going to fail.

**Comment by fiammybe** [comment]
Thanks, Closing this and I will create a new ticket for the downloads module.
