### ISSUE TITLE
Image manager database error on load

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#803]
## Describe the bug
When I go to the image manager after logging in, I get the following error message :
`Fatal error: Uncaught Aura\Sql\Exception\MissingParameter: Parameter 'l' is missing from the bound values in /home/xxx/domains/xxx/public_html/beta/vendor/aura/sql/src/Parser/AbstractParser.php:239 Stack trace: #0 /home/xxx/domains/xxx/public_html/beta/vendor/aura/sql/src/Parser/AbstractParser.php(187): Aura\Sql\Parser\AbstractParser->prepareNamedPlaceholder(':l') #1 /home/xxx/domains/xxx/public_html/beta/vendor/aura/sql/src/Parser/AbstractParser.php(167): Aura\Sql\Parser\AbstractParser->prepareValuePlaceholders(Array) #2 /home/xxx/domains/xxx/public_html/beta/vendor/aura/sql/src/Parser/AbstractParser.php(138): Aura\Sql\Parser\AbstractParser->rebuildPart('SELECT DISTINCT...') #3 /home/xxx/domains/xxx/public_html/beta/vendor/aura/sql/src/Parser/AbstractParser.php(122): Aura\Sql\Parser\AbstractParser->rebuildParts(Array) #4 /home/xxx/domains/impresscms.eu/public_html/beta/vendor/aura/sql/src/Parser/AbstractParser.php(106): Aura\Sql\Parser\ in /home/xxx/domains/xxx/public_html/beta/vendor/aura/sql/src/Parser/AbstractParser.php on line 239`

## To Reproduce
1. Go to 'htdocs/modules/system/admin.php?fct=images'
2. See error

## Expected behavior
I expected to view the image manager :-)

**Comment by fiammybe** [comment]
This was fixed in the mean time.
