### ISSUE TITLE
Can't access "Edit Users" after successful installation

### ISSUE THREAD

**Issue by jrckmcsb** [ImpressCMS/impresscms#807]
## Describe the bug

For this one I will use the ``Edit Users`` functionality but because of database connection I can't access other functionality too.

Composer version 1.10.17 2020-10-30 22:31:58
PHP 7.4.11 (cli) (built: Sep 29 2020 13:18:06) ( ZTS Visual C++ 2017 x64 )
ImpressCMS Version: ImpressCMS 2.0.0 Alpha 10 

## To Reproduce
1. Install Impresscms

2. Login as your admin account

3. Go to ``Users and Groups`` > ``Edit Users``

4. See Error

## Expected behavior
Can access the ``Edit Users`` and other functionalities

## Other notes :

Error message : 

```
Fatal error: Uncaught Error: Call to a member function getCount() on null in C:\xampp\htdocs\impresscms-master\modules\system\admin\users\users.php:57 Stack trace: #0 C:\xampp\htdocs\impresscms-master\modules\system\admin\users.php(293): displayUsers() #1 C:\xampp\htdocs\impresscms-master\modules\system\admin.php(113): include_once('C:\\xampp\\htdocs...') #2 C:\xampp\htdocs\impresscms-master\core\Controllers\LegacyController.php(56): require('C:\\xampp\\htdocs...') #3 C:\xampp\htdocs\impresscms-master\vendor\league\route\src\Strategy\ApplicationStrategy.php(23): ImpressCMS\Core\Controllers\LegacyController->proxy(Object(GuzzleHttp\Psr7\ServerRequest), Array) #4 C:\xampp\htdocs\impresscms-master\vendor\league\route\src\Route.php(69): League\Route\Strategy\ApplicationStrategy->invokeRouteCallable(Object(League\Route\Route), Object(GuzzleHttp\Psr7\ServerRequest)) #5 C:\xampp\htdocs\impresscms-master\vendor\league\route\src\Dispatcher.php(96): League\Route\Route->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(League\Ro in C:\xampp\htdocs\impresscms-master\modules\system\admin\users\users.php on line 57
```

For other issues :  

```

Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\impresscms-master\vendor\aura\sql\src\ExtendedPdo.php:108 Stack trace: #0 C:\xampp\htdocs\impresscms-master\vendor\aura\sql\src\ExtendedPdo.php(108): PDO->__construct('mysql:host=127....', '', '', Array) #1 C:\xampp\htdocs\impresscms-master\core\Providers\DatabaseServiceProvider.php(132): Aura\Sql\ExtendedPdo->connect() #2 C:\xampp\htdocs\impresscms-master\core\Providers\DatabaseServiceProvider.php(46): ImpressCMS\Core\Providers\DatabaseServiceProvider->createDatabaseConnection('mysql', '127.0.0.1', '', '', 0, 'impresscms', 'utf8', NULL, 3306) #3 [internal function]: ImpressCMS\Core\Providers\DatabaseServiceProvider->ImpressCMS\Core\Providers\{closure}() #4 C:\xampp\htdocs\impresscms-master\vendor\league\container\src\Definition\Definition.php(235): call_user_func_array(Object(Closure), Array) #5 C:\xampp\htdocs\impresscms-master\vendor\league\container\src\Definition\Definition.php(198) in C:\xampp\htdocs\impresscms-master\vendor\aura\sql\src\ExtendedPdo.php on line 108
```

**Comment by jrckmcsb** [comment]
Images : 
[impress-help.zip](https://github.com/ImpressCMS/impresscms/files/5543437/impress-help.zip)

**Comment by MekDrop** [comment]
reopeneded to verify
