### ISSUE TITLE
DB issue when accessing blocks admin page

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#899]
## Describe the bug
The blocks admin page gives a DB-related error message : 
```
Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO) in C:\xampp74\htdocs\mastericms\vendor\aura\sql\src\ExtendedPdo.php:108 Stack trace: #0 C:\xampp74\htdocs\mastericms\vendor\aura\sql\src\ExtendedPdo.php(108): PDO->__construct('mysql:host=127....', '', '', Array) #1 C:\xampp74\htdocs\mastericms\core\Providers\DatabaseServiceProvider.php(132): Aura\Sql\ExtendedPdo->connect() #2 C:\xampp74\htdocs\mastericms\core\Providers\DatabaseServiceProvider.php(46): ImpressCMS\Core\Providers\DatabaseServiceProvider->createDatabaseConnection('mysql', '127.0.0.1', '', '', 0, 'impresscms', 'utf8', NULL, 3306) #3 [internal function]: ImpressCMS\Core\Providers\DatabaseServiceProvider->ImpressCMS\Core\Providers\{closure}() #4 C:\xampp74\htdocs\mastericms\vendor\league\container\src\Definition\Definition.php(235): call_user_func_array(Object(Closure), Array) #5 C:\xampp74\htdocs\mastericms\vendor\league\container\src\Definition\Definition.php(198): League\Container\Definition\ in C:\xampp74\htdocs\mastericms\vendor\aura\sql\src\ExtendedPdo.php on line 108
```

**Comment by fiammybe** [comment]
This is in the installation with the install notification #898, perhaps it is linked with that (incomplete DB creation/migration)

**Comment by fiammybe** [comment]
page works now.
