### ISSUE TITLE
DB Issue when accessing tags page in ACP

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#900]
## Describe the bug
When accessing the tags page, I get the following error message 👍 
``` 
Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mastericms.ib453bad6_system_tags' doesn't exist in C:\xampp74\htdocs\mastericms\vendor\aura\sql\src\AbstractExtendedPdo.php:558 Stack trace: #0 C:\xampp74\htdocs\mastericms\vendor\aura\sql\src\AbstractExtendedPdo.php(558): PDOStatement->execute() #1 C:\xampp74\htdocs\mastericms\core\Models\AbstractExtendedHandler.php(436): Aura\Sql\AbstractExtendedPdo->perform('SELECT `id`, `t...', Array) #2 C:\xampp74\htdocs\mastericms\core\View\Table\Table.php(415): ImpressCMS\Core\Models\AbstractExtendedHandler->getObjects(Object(ImpressCMS\Core\Database\Criteria\CriteriaCompo), true, true, 'SELECT `id`, `t...', false) #3 C:\xampp74\htdocs\mastericms\core\View\Table\Table.php(696): ImpressCMS\Core\View\Table\Table->fetchObjects(false) #4 C:\xampp74\htdocs\mastericms\core\View\Table\Table.php(836): ImpressCMS\Core\View\Table\Table->render(true, false) #5 C:\xampp74\htdocs\mastericms\modules\system\admin\tags.php(72): ImpressCMS\Core\View\Table in C:\xampp74\htdocs\mastericms\vendor\aura\sql\src\AbstractExtendedPdo.php on line 558
```
This could be related to #898 and #899, it is on the same installation (no other one at the moment)

**Comment by fiammybe** [comment]
This issue is still present. Impossible to open the ACP on a new installation with the latest source.

**Comment by fiammybe** [comment]
currently this looks to be resolved
